### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by Maximaximum** [jeffling/angular-jl-tether#10]
Hi!

Could you please release a new package version? The master branch contains an important fix (https://github.com/jeffling/angular-jl-tether/pull/7) but there hasn't been a new version release since then.

Thanks!

**Comment by jeffling** [comment]
done.

**Comment by Maximaximum** [comment]
Not sure what's wrong, but when I try to install the package via bower, it says "No tag found that was able to satisfy 0.1.2"

**Comment by Maximaximum** [comment]
Perhaps the problem occurrs because there is no 0.1.2 tag in the github repository?

@jeffling could you please check?

**Comment by jeffling** [comment]
@Maximaximum Hey, I've pushed a tag `v0.1.2` as generated by npm. Sorry about before - i wasn't spending much time on it.

**Comment by Maximaximum** [comment]
Thanks a lot! Working now.
